[versions]
androidGradlePlugin = "8.7.1"
androidx-coreKtx = "1.13.1"
appcompat = "1.7.0"
cardview = "1.0.0"
kotlin = "2.0.21"
leanback = "1.0.0"
material = "1.12.0"
recyclerview = "1.3.2"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-coreKtx" }
androidx-leanback = { module = "androidx.leanback:leanback", version.ref = "leanback" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }